/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bfst;

import java.io.File;
import java.io.IOException;

import bfst.controllers.MainController;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class App extends Application {
    static Stage primaryStage;

    @Override
    public void start(Stage primaryStage) throws Exception {
        this.primaryStage = primaryStage;
        Parent root = App.loadFXML("main");
        primaryStage.setTitle("LLamp");
        primaryStage.setScene(new Scene(root));
        primaryStage.show();
    }

    public static Parent loadFXML(String filename) throws IOException {
        FXMLLoader fxmlLoader = new FXMLLoader(App.class.getResource("views/" + filename + ".fxml"));
        fxmlLoader.setController(new MainController(primaryStage));
        return fxmlLoader.load();
    }

    public static void main(String[] args) {
        App.launch(args);
    }


}
