/*
 * This Java source file was generated by the Gradle 'init' task.

package bfst;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class FirstJunit5Test {

    @Test public void testAppHasAGreeting() {
        assertEquals("hello", "hello");
        // TODO: Actually test something
    }
}
*/